package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TestingClass implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer intField;
	private java.lang.String inputString;
	private java.lang.String outputString;
	private java.lang.Long longField;

	private java.lang.Double doubleField;

	private java.math.BigDecimal bigField;

	public TestingClass() {
	}

	public java.lang.Integer getIntField() {
		return this.intField;
	}

	public void setIntField(java.lang.Integer intField) {
		this.intField = intField;
	}

	public java.lang.String getInputString() {
		return this.inputString;
	}

	public void setInputString(java.lang.String inputString) {
		this.inputString = inputString;
	}

	public java.lang.String getOutputString() {
		return this.outputString;
	}

	public void setOutputString(java.lang.String outputString) {
		this.outputString = outputString;
	}

	public java.lang.Long getLongField() {
		return this.longField;
	}

	public void setLongField(java.lang.Long longField) {
		this.longField = longField;
	}

	public java.lang.Double getDoubleField() {
		return this.doubleField;
	}

	public void setDoubleField(java.lang.Double doubleField) {
		this.doubleField = doubleField;
	}

	public java.math.BigDecimal getBigField() {
		return this.bigField;
	}

	public void setBigField(java.math.BigDecimal bigField) {
		this.bigField = bigField;
	}

	public TestingClass(java.lang.Integer intField,
			java.lang.String inputString, java.lang.String outputString,
			java.lang.Long longField, java.lang.Double doubleField,
			java.math.BigDecimal bigField) {
		this.intField = intField;
		this.inputString = inputString;
		this.outputString = outputString;
		this.longField = longField;
		this.doubleField = doubleField;
		this.bigField = bigField;
	}

}